# https://docs.travis-ci.com/user/languages/cpp/
language: cpp

# compile with gcc
compiler: gcc

# install dependencies
install:
    - sudo apt-get install -y libboost-all-dev libssl-dev libevent-dev libqrencode-dev libdb++-dev

script:
    # generate the build configurator files
    - ./autogen.sh
    # generate makefiles
    - ./configure --with-incompatible-bdb --prefix=$(pwd)
    # compile
    - make
    # compile and deploy
    - make install
  